- name: "Install git"
  ansible.builtin.include_tasks: install/main.yml

- name: "Configure git"
  ansible.builtin.include_tasks: config/main.yml

- name: "Export utility script and cmds for other roles to use"
  ansible.builtin.include_tasks: exports/main.yml

